# Exported from Render on 2026-08-10T22:46:20Z
version: "1"
projects:
  - name: Until
    environments:
      - name: Production
        services:
          - type: web
            name: until
            runtime: static
            repo: https://github.com/emidiomorgia/until
            branch: release/render
            buildCommand: npm run build
            staticPublishPath: dist
            domains:
              - until.morgia.info
            autoDeployTrigger: commit
            buildFilter:
              paths:
                - frontend/**
            rootDir: frontend
            routes:
              - type: rewrite
                source: /*
                destination: /index.html
